### ISSUE TITLE
new problem when starting dataflow:   missing a property named 'outputFirestoreCollectionNamePrefix'.

### ISSUE THREAD

**Issue by lachlancoin** [allenday/nanostream-dataflow#101]
Using the latest pull
Command:
java -cp ./nanostream-dataflow/NanostreamDataflowMain/target/NanostreamDataflowMain-1.0-SNAPSHOT.jar  com.google.allenday.nanostream.NanostreamApp  --runner=org.apache.beam.runners.dataflow.DataflowRunner  --region=asia-northeast1  --project=nano-stream1  --streaming=true  --processingMode=species  --inputDataSubscription=projects/nano-stream1/subscriptions/dataflow_species  --alignmentWindow=20  --statisticUpdatingDelay=30  --servicesUrl=http://10.146.0.18  --bwaEndpoint=/cgi-bin/bwa.cgi  --bwaDatabase=genomeDB.fasta  --kAlignEndpoint=/cgi-bin/kalign.cgi  --outputFirestoreCollectionNamePrefix=NEW4_2019  --outputFirestoreStatisticDocumentName=statistic_document  --resistanceGenesList=gs://nano-stream1/Databases/resFinder/geneList  --alignmentBatchSize=500

Error
Exception in thread "main" java.lang.IllegalArgumentException: Class interface com.google.allenday.nanostream.NanostreamPipelineOptions missing a property named 'outputFirestoreCollectionNamePrefix'.
        at org.apache.beam.sdk.options.PipelineOptionsFactory.parseObjects(PipelineOptionsFactory.java:1614)
        at org.apache.beam.sdk.options.PipelineOptionsFactory.access$400(PipelineOptionsFactory.java:115)
        at org.apache.beam.sdk.options.PipelineOptionsFactory$Builder.as(PipelineOptionsFactory.java:298)
        at com.google.allenday.nanostream.NanostreamApp.main(NanostreamApp.java:69)

**Comment by lachlancoin** [comment]
Ah, sorry I see, this parameter is no longer needed. Understood!
