### ISSUE TITLE
simulator README example fails

### ISSUE THREAD

**Issue by allenday** [allenday/nanostream-dataflow#35]
set variables:
```
# docker image to use
IMAGE=allenday/nanostream-dataflow-simulator
# this is the path to the TSV as described above
SOURCE_FILE=gs://nanostream-dataflow-demo-data/simulator/20170320_GN_179_timestamped_60x.dilate_60x.tsv
# to which bucket will simulated reads be uploaded?
DESTINATION_BUCKET='nanostream-dataflow-qc-simulator'
# [optional] acceleration factor for timestamps
PUBLISHING_SPEED=1
GOOGLE_CLOUD_PROJECT=`gcloud config get-value project`
```

run docker:
```
docker run \
    -e GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT \
    -e SOURCE_FILE=$SOURCE_FILE \
    -e DESTINATION_BUCKET=$DESTINATION_BUCKET \
    -e PUBLISHING_SPEED=$PUBLISHING_SPEED \
    $IMAGE
```

TSV path does not resolve:
```
Traceback (most recent call last):
  File "simulator.py", line 106, in <module>
    download_gsc_file(source_bucket_name, source_gsc_filename, source_filename)
  File "simulator.py", line 80, in download_gsc_file
    blob.download_to_filename(destination_file_name)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 569, in download_to_filename
    with open(filename, 'wb') as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: 'simulator/20170320_GN_179_timestamped_60x.dilate_60x.tsv'
```

But it is valid:
```
gsutil ls -l $SOURCE_FILE
   2895343  2019-02-10T14:29:08Z  gs://nanostream-dataflow-demo-data/simulator/20170320_GN_179_timestamped_60x.dilate_60x.tsv
TOTAL: 1 objects, 2895343 bytes (2.76 MiB)
```

**Comment by allenday** [comment]
https://github.com/allenday/nanostream-dataflow/blob/master/simulator/README.md

**Comment by allenday** [comment]
Seems that we don't handle directories here:
https://github.com/allenday/nanostream-dataflow/blob/d90b4e5eba4cc13654d5f1f3b86f11147d3cde7d/simulator/simulator.py#L82

**Comment by Pseverin** [comment]
Fixed in https://github.com/allenday/nanostream-dataflow/pull/46
There was a problem with caching SOURCE_FILE that contains subfolders in file path

**Comment by allenday** [comment]
confirmed fixed.
