### ISSUE TITLE
`docker run` fails for fasta_formatter

### ISSUE THREAD

**Issue by allenday** [allenday/nanostream-dataflow#39]
https://github.com/allenday/nanostream-dataflow/blob/ef69572d655632c1f567cdbda4596493733725b9/fasta_formatter/Dockerfile#L9

set environment:
```
GOOGLE_CLOUD_PROJECT=`gcloud config get-value project`
# docker image to use
IMAGE=allenday/nanostream-dataflow-fasta-formatter
# no need to change this.
SOURCE_MOUNT=/data
# directory where input FASTA files can be found.
# it needs to be in or below `pwd`.
SOURCE_FOLDER=eg
# this is the path to the TSV as described above.
SOURCE_FILE=in.fa
# to which bucket will records be written?
DESTINATION_BUCKET='nanostream-dataflow-qc-fasta-formatter'
# to which folder will records be written?
DESTINATION_FOLDER=fasta_output/resistant/
```

run docker:
```
docker run \
    -v $(pwd)/$SOURCE_FOLDER:$SOURCE_MOUNT \
    -v $(pwd)/gcloud_keys:/gcloud_keys/ \
    -e GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT \
    -e GOOGLE_APPLICATION_CREDENTIALS='/gcloud_keys/gcloud_credentials.json' \
    -e SOURCE_FILE=$SOURCE_MOUNT/$SOURCE_FILE \
    -e DESTINATION_BUCKET=$DESTINATION_BUCKET \
    -e DESTINATION_FOLDER=$DESTINATION_FOLDER \
    $IMAGE
```

error message:
```
$ docker run     -v $(pwd)/$SOURCE_FOLDER:$SOURCE_MOUNT     -v $(pwd)/gcloud_keys:/gcloud_keys/     -e GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT     -e GOOGLE_APPLICATION_CREDENTIALS='/gcloud_keys/gcloud_credentials.json'     -e SOURCE_FILE=$SOURCE_MOUNT/$SOURCE_FILE     -e DESTINATION_BUCKET=$DESTINATION_BUCKET     -e DESTINATION_FOLDER=$DESTINATION_FOLDER     $IMAGE
Adding 97 symbols
Adding 94 symbols
Uploading 193 symbols
Traceback (most recent call last):
  File "/formatter/formatter.py", line 115, in <module>
    accumulate_data_and_upload_to_gcs_if_needed(False)
  File "/formatter/formatter.py", line 83, in accumulate_data_and_upload_to_gcs_if_needed
    upload_file(output_file_data, file_name, "text/plain", destination_bucket_name)
  File "/formatter/formatter.py", line 23, in upload_file
    bucket = storage.Client().get_bucket(destination_bucket_name)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/storage/client.py", line 225, in get_bucket
    bucket.reload(client=self)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/storage/_helpers.py", line 108, in reload
    _target_object=self)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/_http.py", line 293, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 GET https://www.googleapis.com/storage/v1/b/nanostream-dataflow-qc-fasta-formatter?projection=noAcl: Not Found
```

**Comment by Pseverin** [comment]
It looks like, you are trying to write to the bucket which wasn't created (`nanostream-dataflow-qc-fasta-formatter`)

I have success with `DESTINATION_BUCKET='testing_simulator_marva_albacore_fastq'`
```
Adding 97 symbols
Adding 94 symbols
Uploading 193 symbols
Output file names: ['gs://testing_simulator_marva_albacore_fastq/fasta_output/resistant/0.fasta']
```
and have the same error when trying to change bucket name `DESTINATION_BUCKET='not_existed_testing_simulator_marva_albacore_fastq'`
```
Adding 97 symbols
Adding 94 symbols
Uploading 193 symbols
Traceback (most recent call last):
  File "/formatter/formatter.py", line 115, in <module>
    accumulate_data_and_upload_to_gcs_if_needed(False)
  File "/formatter/formatter.py", line 83, in accumulate_data_and_upload_to_gcs_if_needed
    upload_file(output_file_data, file_name, "text/plain", destination_bucket_name)
  File "/formatter/formatter.py", line 23, in upload_file
    bucket = storage.Client().get_bucket(destination_bucket_name)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/storage/client.py", line 225, in get_bucket
    bucket.reload(client=self)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/storage/_helpers.py", line 108, in reload
    _target_object=self)
  File "/usr/local/lib/python3.7/site-packages/google/cloud/_http.py", line 293, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 GET https://www.googleapis.com/storage/v1/b/not_existed_testing_simulator_marva_albacore_fastq?projection=noAcl: Not Found
```
